version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: src/App/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432


